/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'root' at '22/12/16 03:04' with Gradle 3.2.1
 *
 * @author root, @date 22/12/16 03:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
